### PR TITLE
re-organize files into folder

### PR DESCRIPTION
**Pull request by phineas-pta**
make a `jaapy/` folder and move various scripts into it, instead of have them scattered around

### CODE REVIEW

**Comment by janvarev** [comment]
It's a good idea entirely, but not a good solution, really.

There is a plans that jaapy and chain-img-processors could be updated anytime from their origins (there are separate projects, that are progress independently). Chainging their structure here is mean break the ability to upgrade them from sources.

**Comment by janvarev** [comment]
jaapy is used at least in my 3 public projects, so it can't be edited easily

**Comment by janvarev** [comment]
Files reorganized in https://github.com/RichardErkhov/Richard-roop/pull/10

**Comment by phineas-pta** [comment]
how about git submodule ?
https://github.blog/2016-02-01-working-with-submodules/

**Comment by janvarev** [comment]
@phineas-pta Idea, but it require additional efforts to support this. Submodule has their own rules to update, not ideally support with IDE usually.
I think RP #10 solves the problem mostly.

**Comment by phineas-pta** [comment]
ok no prob for me

i've never used submodule so idk

**Pull request closed without merging**
